INSERT INTO ds_khoa VALUES 
    ('TNHO' , '(ngành) SP Hóa học'),
    ('TT' , 'Khoa Thư viện - Văn phòng'),
    ('LULK' , 'Luật Kinh doanh (không còn dùng)'),
    ('TTTV' , '(ngành) Thư viện - Văn phòng'),
    ('GTGT' , '(ngành) Giáo dục Tiểu học'),
    ('TE' , 'Khoa Tài chính - Kế toán'),
    ('NTNH' , '(ngành) SP Âm nhạc'),
    ('TDTU' , '(ngành) Toán ứng dụng'),
    ('LULU' , '(ngành) Luật'),
    ('MOCM' , '(ngành) Công nghệ kỹ thuật môi trường'),
    ('TDTO' , '(ngành) SP Toán học'),
    ('LC' , 'Khoa Giáo dục chính trị'),
    ('XHSU' , '(ngành) SP Lịch sử'),
    ('NNSA' , '(ngành) SP Tiếng Anh'),
    ('XHXH' , '(khoa) SP Khoa học Xã hội'),
    ('LULH' , 'Luật Hành chinh (không còn dùng)'),
    ('NNTA' , '(ngành) Tiếng Anh (Thương mại và du lịch)'),
    ('QG' , 'Khoa Giáo dục'),
    ('TETN' , '(ngành) Tài chính - Ngân hàng'),
    ('DVDV' , '(ngành) Kỹ thuật điện tử - viễn thông'),
    ('XHVA' , '(ngành) SP Ngữ văn'),
    ('VDVI' , '(ngành) Việt Nam học (Văn hóa - Du lịch)'),
    ('TNLI' , '(ngành) SP Vật lý'),
    ('NTNT' , '(khoa) Nghệ thuật'),
    ('TTQV' , '(ngành) Quản trị văn phòng'),
    ('TN' , 'Khoa SP Khoa học Tự nhiên'),
    ('XH' , 'Khoa SP Khoa học Xã hội'),
    ('VDQT' , '(ngành) Quốc tế học'),
    ('VD' , 'Khoa Văn hóa và Du lịch'),
    ('QGQG' , '(ngành) Quản lý Giáo dục'),
    ('NN' , 'Khoa Ngoại ngữ'),
    ('TNSI' , '(ngành) SP Sinh học'),
    ('NTNA' , '(ngành) Thanh nhạc'),
    ('TEKE' , '(ngành) Kế toán'),
    ('MIMI' , '(ngành) SP Mỹ thuật'),
    ('XHDI' , '(ngành) SP Địa lý'),
    ('MOKM' , '(ngành) Khoa học môi trường'),
    ('QDQK' , '(ngành) Quản trị kinh doanh'),
    ('DV' , 'Khoa Điện tử viễn thông'),
    ('LCGD' , '(ngành) Giáo dục Chính trị'),
    ('CTCT' , '(ngành) Công nghệ thông tin'),
    ('TD' , 'Khoa Toán - ứng dụng'),
    ('MO' , 'Khoa Môi trường'),
    ('QGTL' , '(ngành) Tâm lí học'),
    ('GMGM' , '(ngành) Giáo dục Mầm non'),
    ('NT' , 'Khoa Nghệ thuật')